-- AlterTable
ALTER TABLE "Menu" ALTER COLUMN "id" SET DEFAULT '',
ALTER COLUMN "permissions" DROP NOT NULL,
ALTER COLUMN "permissions" SET DATA TYPE TEXT,
ALTER COLUMN "path_ids" SET NOT NULL,
ALTER COLUMN "path_ids" SET DEFAULT '[]',
ALTER COLUMN "path_ids" SET DATA TYPE TEXT,
ALTER COLUMN "path_names" SET NOT NULL,
ALTER COLUMN "path_names" SET DEFAULT '[]',
ALTER COLUMN "path_names" SET DATA TYPE TEXT;
